# Generated by Django 4.0.5 on 2022-08-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_name', models.CharField(max_length=500)),
                ('stall_location', models.CharField(max_length=500)),
                ('uuid', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
            ],
        ),
    ]
