# Generated by Django 4.0.5 on 2022-08-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_viewer_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='class_user',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='section',
        ),
    ]
